POST http://localhost:8000/user/signup
Content-Type: application/json

{
  "firstName": "seraj",
  "lastName": "seraj",
  "email": "seraj",
  "password": "seraj"
}

###
### Create a new deck
POST localhost:8000/decks
Content-Type: application/json

{
  "name": "Test D",
  "cover": "https://picsum.photos/100",
  "description": "Test A description",
  "flashCards": []
}

###

